/**
 * Bakes the Atlantic chart's coastline and graticule into src/generated/atlantic.ts,
 * so the page needs no geodata or projection library at runtime.
 *
 * Source: Natural Earth 1:110m land via the world-atlas package. Projection: Mercator,
 * the nautical convention, fitted to the box lon −100…15, lat 5…62 and clipped to the
 * 800×520 viewBox. The projection's scale and translate are written out too, so
 * src/sections/challenge.ts can place the start/finish lines with the same maths.
 *
 *   npm run chart
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { geoGraticule, geoMercator, geoPath } from 'd3-geo'
import { feature } from 'topojson-client'

const require = createRequire(import.meta.url)
const topology = require('world-atlas/land-110m.json')
const land = feature(topology, topology.objects.land)

const WIDTH = 800
const HEIGHT = 520
const BOX = { lon: [-100, 15], lat: [5, 62] }

const frame = {
  type: 'Polygon',
  coordinates: [
    [
      [BOX.lon[0], BOX.lat[0]],
      [BOX.lon[0], BOX.lat[1]],
      [BOX.lon[1], BOX.lat[1]],
      [BOX.lon[1], BOX.lat[0]],
      [BOX.lon[0], BOX.lat[0]],
    ],
  ],
}

const projection = geoMercator().fitSize([WIDTH, HEIGHT], frame).clipExtent([
  [0, 0],
  [WIDTH, HEIGHT],
])
const path = geoPath(projection).digits(1)

const landPath = path(land) ?? ''
const graticulePath = path(geoGraticule().step([10, 10])()) ?? ''
const [tx, ty] = projection.translate()

const out = `// Generated by scripts/build-chart.mjs — do not edit. Run \`npm run chart\` to rebuild.
// Natural Earth 1:110m land (world-atlas), Mercator, lon ${BOX.lon[0]}…${BOX.lon[1]}, lat ${BOX.lat[0]}…${BOX.lat[1]}.

export const CHART = {
  width: ${WIDTH},
  height: ${HEIGHT},
  /** d3 geoMercator scale (pixels per radian). */
  scale: ${projection.scale().toFixed(4)},
  translate: [${tx.toFixed(3)}, ${ty.toFixed(3)}] as const,
  land: '${landPath}',
  graticule: '${graticulePath}',
} as const
`

const dir = fileURLToPath(new URL('../src/generated/', import.meta.url))
mkdirSync(dir, { recursive: true })
const file = join(dir, 'atlantic.ts')
writeFileSync(file, out)
console.log(`wrote ${file}  (${(out.length / 1024).toFixed(1)} kB, land path ${(landPath.length / 1024).toFixed(1)} kB)`)
